# Use the latest Ubuntu image as base
FROM ubuntu:latest

# Update APT package repo
RUN apt-get update

# Update installed packages
RUN apt-get upgrade -y

# Command to echo "Hello, world!"
CMD echo "Hello, World!"